(mes
 (meta (engine 'AI5) (charset "English") (dictbase 128))
(dict-build)
 (set-arr~ @ 7 1)
 (set-arr~ @ 3 0)
 (set-arr~ @ 2 45056)
 (set-arr~ @ 7 0)
 (load "mouse.dat" 49152)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "19.pd8")
 (proc 15)
 (set-arr~ @ 6 1)
 (image "t.pd8")
 (proc 16)
 (set-arr~ @ 7 1)
 (set-arr~ @ 1 4096)
 (set-arr~ @ 6 1)
 (image "tan.pd8")
 (set-arr~ @ 6 0)
 (set-arr~ @ 7 0)
 (load "t.s4" (~ @ 2))
 (animate 0 0 0)
 (animate 1 0)
 (set-arr~ @ 7 0)
 (while
  (== 1 1)
  (<>
   (set-arr~ @ 20 (+ (&& (~ @ 20) 65280) 0))
   (set-arr~ @ 21 (+ 256 16))
   (set-arr~ @ 20 (// (&& (~ @ 20) 65399) 128))
   (set-arr~ @ 20 (&& (~ @ 20) 4095))
   (color 8)
   (set-arr~ @ 6 0)
   (set-arr~ @ 13 15 322 64 391)
   (clear)
   (if-else (== N 2)
     (<>
      (text #:color 7 "" 0 ": Um... H-hey, Ako.")
      (wait)
      (text #:color 2 "Ako: Hmm? Oh, yeah, hi, " 0 ".")
      (wait)
      (text #:color 7 "" 0 ": So... yeah, busy holding down the fort, I see.")
      (wait)
      (text #:color 2 "Ako: I... guess? I mean, it can't be helped. Mako's pulling overtime at the nurse's office.")
      (wait)
      (text #:color 7 "" 0 ": That right? She tending more sprained ankles or just taking inventory?")
      (wait)
      (text #:color 2 "Ako: Pretty sure it's just inventory, but I honestly don't kno-")
      (wait)
      (text #:color 2 "Ako: Hold on a sec, why do you wanna know?")
      (wait)
      (text #:color 7 "" 0 ": Oh, well, about that...")
      (wait)
      (text #:color 2 "Ako: " 0 ", if you've got something on your mind, I'd much rather we forgo the endless back-and-forth.")
      (wait)
      (text #:color 7 "" 0 ": You know what? Fair enough.")
      (wait)
      (cond
       ((< (: 106) 6) (<> (text #:color 2 "Ako: What is it?") (wait)))
       ((> (: 106) 5) (<> (text #:color 2 "Ako: What?") (wait)))
       (else (<>)))
      (text #:color 7 "" 0 ": Okay, so... let me preface by saying this isn't some kind of joke. I know given… everything… that's might be difficult to believe. But I'm entirely serious.")
      (wait)
      (text #:color 7 "" 0 ": And, yes, I know we're both a bit young for me to be thinking about this. Hell, you're two years older than me, and you just turned old enough to drink.")
      (wait)
      (text #:color 7 "" 0 ": But I think there's a future for the both of us. And I want to make things official.")
      (wait)
      (text #:color 2 "Ako: " 0 "...")
      (wait)
      (text #:color 7 "" 0 ": Y-yes?")
      (wait)
      (cond
       ((< (: 106) 3)
        (<>
         (sound 1)
         (set-var I 13)
         (proc 26)
         (text #:color 2 "Ako: " 0 "... Not to put too fine a point on it... but I absolutely fucking loathe you.")
         (wait)
         (text #:color 7 "" 0 ": Gwaaaahhh...")
         (wait)
         (sound 1)
         (set-var I 47)
         (proc 26)
         (text #:color 2 "Ako: Actually, even that's being too generous. The very sight of you makes me want to vomit.")
         (wait)
         (text #:color 7 "" 0 ": A-Ako...")
         (wait)
          (text #:color 2 "Ako: " 0 " every time you come to this drugstore it makes me want to close the shop.")
         (wait)
         (text #:color 7 "" 0 ": N-no way...")
         (wait)
         (text #:color 2 "Ako: If possible, I'd rather not see you around here anymore. Could you drop by by another drugstore from now on?")
         (wait)
         (text #:color 7 "" 0 ": N-No way...")
         (wait)
         (text #:color 2 "Ako: So, could you go home...?
And " 0 ", if you keep talking I'll
start feeling depressed.")
         (wait)
         (set-reg: 821 1)
         (slot 1 1)
         (mes-jump "y15.mes")))
       ((< (: 106) 6)
        (<>
         (sound 1)
         (set-var I 13)
         (proc 26)
         (text #:color 2 "Ako: I... " 0 " I don't like you")
         (wait)
         (text #:color 7 "" 0 ": Gwaaaahhh...")
         (wait)
         (sound 1)
         (set-var I 47)
         (proc 26)
         (text #:color 2 "Ako: I'm sorry but... I'd like to forget we even
had this conversation.")
         (wait)
         (text #:color 7 "" 0 ": A-Ako...")
         (wait)
         (text #:color 2 "Ako: I don't even know what I'm supposed to do
during a confession... It's enough to make me
feel sick.")
         (wait)
         (text #:color 7 "" 0 ": N-No way...")
         (wait)
         (text #:color 2 "Ako: If possible, I'd rather not see you around
here anymore. Could you drop by by another
drugstore from now on?")
         (wait)
         (text #:color 7 "" 0 ": N-no way...")
         (wait)
         (text #:color 2 "Ako: So, could you go home...? And " 0 ", if you keep talking I'll start feeling depressed.")
         (wait)
         (set-reg: 821 1)
         (slot 1 1)
         (mes-jump "y15.mes")))
       ((< (: 106) 13)
        (<>
         (sound 1)
         (set-var I 12)
         (proc 26)
         (text #:color 2 "Ako: " 0 " I like you too as well, but...")
         (wait)
         (text #:color 7 "" 0 ": (Fuck yeah!!)")
         (wait)
         (text #:color 2 "Ako: After some thinking...
You're quite close with other girls as well,
so...")
         (wait)
         (sound 1)
         (set-var I 46)
         (proc 26)
         (text #:color 7 "" 0 ": Out of all of them
I like you the most.")
         (wait)
         (text #:color 2 "Ako: I'm really sorry, " 0 ". You're a dear friend and I care about you. And, for the record, it leaves a bad taste in my mouth to use clichés, but in this case? It's not you, it's me.")
         (wait)
         (text #:color 7 "" 0 ": This is really how it goes, huh?")
         (wait)
         (text #:color 2 "Ako: Believe me, if I had pills for heartbreak behind this counter, I'd give you our whole stock.")
         (wait)
         (text #:color 7 "" 0 ": ...")
         (wait)
         (text #:color 2 "Ako: " 0 "H-hey, chin up. We're still friends, alright? You can always stop by whenever you wanna hang out.")
         (wait)
         (text #:color 7 "" 0 ": ...")
         (wait)
         (set-reg: 821 2)
         (slot 1 1)
         (mes-jump "y15.mes")))
       ((< (: 106) 16)
        (<>
         (sound 1)
         (set-var I 21)
         (proc 26)
         (text #:color 2 "Ako: I am so, so happy.")
         (wait)
         (text #:color 2 "Ako: " 0 "... I've never dreamed you'd ask me out.")
         (wait)
         (sound 1)
         (set-var I 29)
         (proc 26)
         (text #:color 7 "" 0 ": Ako...")
         (wait)
         (text #:color 2 "Ako: " 0 " I'd do anything for you... Your wish is my command.")
         (wait)
         (text #:color 7 "" 0 ": ...")
         (wait)
         (text #:color 2 "Ako: So, please... Don't abandon me.")
         (wait)
         (text #:color 7 "" 0 ": O-of course.")
         (wait)
         (text #:color 2 "Ako: " 0 "...")
         (wait)
         (text #:color 7 "" 0 ": Ako...")
         (wait)
         (text #:color 2 "Ako: " 0 "!!")
         (wait)
         (text #:color 7 "" 0 ": Ako!!")
         (wait)
         (text #:color 2 "Ako: " 0 "!!!")
         (wait)
         (set-reg: 821 3)
         (slot 1 1)
         (mes-jump "y15.mes")))
       (else (<>))))
     (<>))))
 (set-arr~ @ 7 1))